plugins {
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

version = '10.2.0'
group = 'com.jujutsu.jujutsucraftaddon'
archivesBaseName = 'jujutsucraftaddon'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'parchment', version: '2023.09.03-1.20.1'

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    copyIdeResources = true

    runs {
        client {
            jvmArgs += [
                    "-Xms256M", "-Xmx4500M", "-XX:+UseG1GC", "-XX:MinHeapFreeRatio=5", "-XX:MaxHeapFreeRatio=10", "-XX:+ParallelRefProcEnabled", "-XX:MaxGCPauseMillis=200",
                    "-XX:+UnlockExperimentalVMOptions", "-XX:+DisableExplicitGC", "-XX:+AlwaysPreTouch",
                    "-XX:G1NewSizePercent=40", "-XX:G1MaxNewSizePercent=50", "-XX:G1HeapRegionSize=16M",
                    "-XX:G1ReservePercent=15", "-XX:G1HeapWastePercent=5", "-XX:G1MixedGCCountTarget=4",
                    "-XX:InitiatingHeapOccupancyPercent=15", "-XX:G1MixedGCLiveThresholdPercent=90",
                    "-XX:G1RSetUpdatingPauseTimePercent=5", "-XX:SurvivorRatio=32", "-XX:+PerfDisableSharedMem",
                    "-XX:MaxTenuringThreshold=1", "-XX:+AllowEnhancedClassRedefinition", "-Djjku.opSukunaMetrics=true" ,"-Djjkur.debug=true", "-Dusing.aikars.flags=https://mcflags.emc.gs/", "-Daikars.new.flags=true"
            ]
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            environment '__NV_PRIME_RENDER_OFFLOAD', '1'
            environment '__GLX_VENDOR_LIBRARY_NAME', 'nvidia'

            mods {
                jujutsucraftaddon {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                jujutsucraftaddon {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                jujutsucraftaddon {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.10'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    implementation fg.deobf("curse.maven:sorceryfight-471288:7985964")
    implementation fg.deobf("curse.maven:jjsk-1128285:7762065")
    implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.20.1:4.8.3')
    implementation fg.deobf('dev.kosmx.player-anim:player-animation-lib-forge:1.0.2-rc1+1.20')
    implementation fg.deobf("curse.maven:starlight-526854:4631193")
    //opcional
    implementation fg.deobf("curse.maven:architectury_api-419699:5137938")
//    implementation fg.deobf("curse.maven:jujutsucraft-ve-visual-effects-1177064:6335231")
    compileOnly fg.deobf("curse.maven:modern-jujutsu-1331913:7883228")
}

mixin {
    add sourceSets.main, 'mixins.jujutsucraftaddon.refmap.json'

    config 'mixins.jujutsucraftaddon.json'

    debug.verbose = true
    debug.export = true
    dumpTargetOnFailure = true

    quiet
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

repositories {
    maven {
        url = 'https://cursemaven.com/'
    }
    maven {
        url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
    }
    maven {
        url = 'https://maven.kosmx.dev/'
    }
}
