//1 - //package com.jujutsu.jujutsucraftaddon.mixins;                                                                                                                                                             │
//        │  2 - //                                                                                                                                                                                                          │
//        │  3 - //import com.jujutsu.jujutsucraftaddon.network.JujutsucraftaddonModVariables;                                                                                                                               │
//        │  4 - //import net.mcreator.jujutsucraft.init.JujutsucraftModMobEffects;                                                                                                                                          │
//        │  5 - //import net.mcreator.jujutsucraft.procedures.RenderCloudProcedure;                                                                                                                                         │
//        │  6 - //import net.minecraft.client.Minecraft;                                                                                                                                                                    │
//        │  7 - //import net.minecraft.world.effect.MobEffect;                                                                                                                                                              │
//        │  8 - //import net.minecraft.world.entity.Entity;                                                                                                                                                                 │
//        │  9 - //import net.minecraft.world.entity.LivingEntity;                                                                                                                                                           │
//        │ 10 - //import net.minecraftforge.eventbus.api.Event;                                                                                                                                                             │
//        │ 11 - //import org.spongepowered.asm.mixin.Mixin;                                                                                                                                                                 │
//        │ 12 - //import org.spongepowered.asm.mixin.injection.At;                                                                                                                                                          │
//        │ 13 - //import org.spongepowered.asm.mixin.injection.Inject;                                                                                                                                                      │
//        │ 14 - //import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;                                                                                                                                       │
//        │ 15 - //                                                                                                                                                                                                          │
//        │ 16 - //import static net.mcreator.jujutsucraft.procedures.RenderCloudProcedure.renderClouds;                                                                                                                     │
//        │ 17 - //                                                                                                                                                                                                          │
//        │ 18 - //@Mixin(value = RenderCloudProcedure.class, priority = -1000)                                                                                                                                              │
//        │ 19 - //public class RenderCloudProcedureMixin {                                                                                                                                                                  │
//        │ 20 - //    @Inject(                                                                                                                                                                                              │
//        │ 21 - //            method = {"execute(Lnet/minecraftforge/eventbus/api/Event;Lnet/minecraft/world/entity/Entity;)V"},                                                                                            │
//        │ 22 - //            at = {@At("HEAD")},                                                                                                                                                                           │
//        │ 23 - //            cancellable = true,                                                                                                                                                                           │
//        │ 24 - //            remap = false                                                                                                                                                                                 │
//        │ 25 - //    )                                                                                                                                                                                                     │
//        │ 26 - //    private static void execute(Event event, Entity entity, CallbackInfo ci) {                                                                                                                            │
//        │ 27 - //        ci.cancel();                                                                                                                                                                                      │
//        │ 28 - //        if (entity != null) {                                                                                                                                                                             │
//        │ 29 - //            double var10000;                                                                                                                                                                              │
//        │ 30 - //            double color;                                                                                                                                                                                 │
//        │ 31 - //            label36: {                                                                                                                                                                                    │
//        │ 32 - //                color = 0.0;                                                                                                                                                                              │
//        │ 33 - //                double distance = 0.0;                                                                                                                                                                    │
//        │ 34 - //                if (entity instanceof LivingEntity) {                                                                                                                                                     │
//        │ 35 - //                    LivingEntity _livEnt0 = (LivingEntity)entity;                                                                                                                                         │
//        │ 36 - //                    if (_livEnt0.hasEffect((MobEffect)JujutsucraftModMobEffects.DOMAIN_EXPANSION.get())) {                                                                                                │
//        │ 37 - //                        var10000 = entity.getPersistentData().getDouble("skill_domain") + 10.0;                                                                                                           │
//        │ 38 - //                        break label36;                                                                                                                                                                    │
//        │ 39 - //                    }                                                                                                                                                                                     │
//        │ 40 - //                }                                                                                                                                                                                         │
//        │ 41 - //                                                                                                                                                                                                          │
//        │ 42 - //                if (entity instanceof LivingEntity) {                                                                                                                                                     │
//        │ 43 - //                    LivingEntity _livEnt = (LivingEntity)entity;                                                                                                                                          │
//        │ 44 - //                    if (_livEnt.hasEffect((MobEffect)JujutsucraftModMobEffects.NEUTRALIZATION.get())) {                                                                                                   │
//        │ 45 - //                        var10000 = (double)_livEnt.getEffect((MobEffect)JujutsucraftModMobEffects.NEUTRALIZATION.get()).getAmplifier();                                                                   │
//        │ 46 - //                        break label36;                                                                                                                                                                    │
//        │ 47 - //                    }                                                                                                                                                                                     │
//        │ 48 - //                }                                                                                                                                                                                         │
//        │ 49 - //                                                                                                                                                                                                          │
//        │ 50 - //                var10000 = 0.0;                                                                                                                                                                           │
//        │ 51 - //            }                                                                                                                                                                                             │
//        │ 52 - //                                                                                                                                                                                                          │
//        │ 53 - //            color = var10000;                                                                                                                                                                             │
//        │ 54 - //            if (color > 10.0) {                                                                                                                                                                           │
//        │ 55 - //                color -= 10.0;                                                                                                                                                                            │
//        │ 56 - //                if ((entity.getCapability(JujutsucraftaddonModVariables.PLAYER_VARIABLES_CAPABILITY, null).orElse(new JujutsucraftaddonModVariables.PlayerVariables())).fog) {                            │
//        │ 57 - //                    if (color == 1.0 || color == 18.0) {                                                                                                                                                  │
//        │ 58 - //                        renderClouds(Minecraft.getInstance().options.getCloudsType(), 192.0, -1.0, 0.0, -2143289344);                                                                                     │
//        │ 59 - //                    }                                                                                                                                                                                     │
//        │ 60 - //                }                                                                                                                                                                                         │
//        │ 61 - //            }                                                                                                                                                                                             │
//        │ 62 - //                                                                                                                                                                                                          │
//        │ 63 - //        }                                                                                                                                                                                                 │
//        │ 64 - //    }                                                                                                                                                                                                     │
//        │ 65 - //}